/*
Copyright Obaydullah.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/AshrafulHaqueToni/crd-controller/pkg/apis/ash.dev/v1alpha1"
	ashdevv1alpha1 "github.com/AshrafulHaqueToni/crd-controller/pkg/client/applyconfiguration/ash.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAshes implements AshInterface
type FakeAshes struct {
	Fake *FakeAshV1alpha1
	ns   string
}

var ashesResource = v1alpha1.SchemeGroupVersion.WithResource("ashes")

var ashesKind = v1alpha1.SchemeGroupVersion.WithKind("Ash")

// Get takes name of the ash, and returns the corresponding ash object, and an error if there is any.
func (c *FakeAshes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Ash, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ashesResource, c.ns, name), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// List takes label and field selectors, and returns the list of Ashes that match those selectors.
func (c *FakeAshes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AshList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ashesResource, ashesKind, c.ns, opts), &v1alpha1.AshList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AshList{ListMeta: obj.(*v1alpha1.AshList).ListMeta}
	for _, item := range obj.(*v1alpha1.AshList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ashes.
func (c *FakeAshes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ashesResource, c.ns, opts))

}

// Create takes the representation of a ash and creates it.  Returns the server's representation of the ash, and an error, if there is any.
func (c *FakeAshes) Create(ctx context.Context, ash *v1alpha1.Ash, opts v1.CreateOptions) (result *v1alpha1.Ash, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ashesResource, c.ns, ash), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// Update takes the representation of a ash and updates it. Returns the server's representation of the ash, and an error, if there is any.
func (c *FakeAshes) Update(ctx context.Context, ash *v1alpha1.Ash, opts v1.UpdateOptions) (result *v1alpha1.Ash, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ashesResource, c.ns, ash), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAshes) UpdateStatus(ctx context.Context, ash *v1alpha1.Ash, opts v1.UpdateOptions) (*v1alpha1.Ash, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ashesResource, "status", c.ns, ash), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// Delete takes name of the ash and deletes it. Returns an error if one occurs.
func (c *FakeAshes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ashesResource, c.ns, name, opts), &v1alpha1.Ash{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAshes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ashesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AshList{})
	return err
}

// Patch applies the patch and returns the patched ash.
func (c *FakeAshes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Ash, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ashesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied ash.
func (c *FakeAshes) Apply(ctx context.Context, ash *ashdevv1alpha1.AshApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Ash, err error) {
	if ash == nil {
		return nil, fmt.Errorf("ash provided to Apply must not be nil")
	}
	data, err := json.Marshal(ash)
	if err != nil {
		return nil, err
	}
	name := ash.Name
	if name == nil {
		return nil, fmt.Errorf("ash.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ashesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeAshes) ApplyStatus(ctx context.Context, ash *ashdevv1alpha1.AshApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Ash, err error) {
	if ash == nil {
		return nil, fmt.Errorf("ash provided to Apply must not be nil")
	}
	data, err := json.Marshal(ash)
	if err != nil {
		return nil, err
	}
	name := ash.Name
	if name == nil {
		return nil, fmt.Errorf("ash.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ashesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Ash{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ash), err
}
